[GLOBAL]
pants_version = "2.21.0"
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
    "pants.backend.python",
    "pants.backend.plugin_development",
]


[python]
interpreter_constraints = ["==3.9.*"]
enable_resolves = true


[python.resolves]
pants-plugins = "pants-plugins/lock.json"
